### ISSUE TITLE
定义Webfont以支持游戏内特殊图标

### ISSUE THREAD

**Issue by Boxkun** [LittleNightmare/remote-party-finder#3]
在common.css内：
添加
`@font-face {
  font-family: 'FFXIV';
  src: url('FFXIV_Lodestone_SSF.ttf') format('truetype'),
       url('FFXIV_Lodestone_SSF.woff') format('woff');
  unicode-range: U+E020-E0DB;
}`

.body
`font-family: FFXIV, sans-serif`

从SE下载以下字体到服务端 /assets ：
`https://img.finalfantasyxiv.com/lds/pc/global/fonts/FFXIV_Lodestone_SSF.woff
 https://img.finalfantasyxiv.com/lds/pc/global/fonts/FFXIV_Lodestone_SSF.ttf`

**Comment by LittleNightmare** [comment]
已支持
